# Generated by Django 3.1.1 on 2020-09-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_tag_image'),
        ('users', '0002_auto_20200918_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tag',
        ),
        migrations.AddField(
            model_name='user',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='tags.Tag'),
        ),
    ]
