# Generated by Django 2.2.7 on 2019-11-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer_rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
