# Generated by Django 2.2.7 on 2019-12-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20191128_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_date']},
        ),
    ]
