# Generated by Django 3.1.1 on 2020-09-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20191205_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='question_title',
        ),
    ]
