# Generated by Django 3.1.1 on 2020-09-22 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_remove_questionanswer_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='questions.questionanswer'),
        ),
    ]
