# Generated by Django 3.1.1 on 2020-09-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_questionanswer_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='content',
            field=models.TextField(max_length=300),
        ),
    ]
