# Generated by Django 3.1.1 on 2020-09-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_tag_image'),
        ('questions', '0011_auto_20200923_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='tags.Tag'),
        ),
    ]
