# Generated by Django 3.1.1 on 2020-12-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20200923_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answervote',
            old_name='answer_vote',
            new_name='vote_value',
        ),
        migrations.RenameField(
            model_name='answervote',
            old_name='answer',
            new_name='voted_parent',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_rank',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='answer_rank',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='questionvote',
            old_name='question_vote',
            new_name='vote_value',
        ),
        migrations.RenameField(
            model_name='questionvote',
            old_name='question',
            new_name='voted_parent',
        ),
    ]
