# Generated by Django 2.2.7 on 2019-11-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_image',
            field=models.ImageField(default='default.jpg', upload_to='tag_image'),
            preserve_default=False,
        ),
    ]
